/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BRACU\14101080
 */
public class ScientificCalculator extends javax.swing.JFrame {
public static int toggle;
public static double answer;
public static int count=0;
public static int inv;

public static boolean ba,bs,bd,bm,bln,blog,bsin,bcos,btan,bex,be,bpi,bf,bpow,br,binv,bper,ban;

    /**
     * 
     * Creates new form ScientificCalculator
     */
    public ScientificCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton26 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(70, 50));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("7");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("8");
        jButton2.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("9");
        jButton3.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("1");
        jButton7.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("2");
        jButton8.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("3");
        jButton9.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("0");
        jButton10.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("(");
        jButton11.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText(")");
        jButton12.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("%");
        jButton13.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("CE");
        jButton14.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("÷");
        jButton15.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("×");
        jButton16.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("-");
        jButton17.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("+");
        jButton18.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton20.setText(".");
        jButton20.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("x!");
        jButton21.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("ln");
        jButton22.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("log");
        jButton23.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("√");
        jButton24.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("x^y");
        jButton25.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton27.setText("sin");
        jButton27.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("cos");
        jButton28.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setText("tan");
        jButton29.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setText("EXP");
        jButton30.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setText("π");
        jButton31.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton33.setText("e");
        jButton33.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setText("Ans/Rnd");
        jButton34.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Rad");
        jToggleButton2.setPreferredSize(new java.awt.Dimension(70, 50));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton26.setText("ClearAll");
        jButton26.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton19.setText("=");
        jButton19.setPreferredSize(new java.awt.Dimension(70, 50));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Inv");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
      
        if(inv==0 || inv%2==0){
        s0=s0+"cos(";
        }
        else{
           s0=s0+"arccos(";  
        }
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        if(inv==0 || inv%2==0){
        s0=s0+"sin(";
        }
        else{
           s0=s0+"arcsin(";  
        }
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"%";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"3";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"2";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"0";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          String s0=jTextField1.getText();
        s0=s0+"1";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"4";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"5";
        jTextField1.setText(s0);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"6";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"7";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"8";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"9";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"(";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+")";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"!";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
         String s0=jTextField1.getText();
        if(inv==0 || inv%2==0){
        s0=s0+"ln(";
    }
        else{
                s0=s0+"e□";
                }
        jTextField1.setText(s0);
    
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        if(inv==0 || inv%2==0)
        {
        s0=s0+"log(";
        
        }
        else{
           s0=s0+"E";  
        }
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        
        String s0=jTextField1.getText();
        if (inv==0 || inv%2==0){
        s0=s0+"√";
        } else 
        {
        s0=s0+"^2";
        }
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
       if (inv==0 || inv%2==0){
        s0=s0+"^";
       }
       else{
           s0=s0+"^1/";
       }
        jTextField1.setText(s0);
        
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        if(inv==0 || inv%2==0){
        s0=s0+"tan(";
        }
        else{
           s0=s0+"arctan(";  
        }
        jTextField1.setText(s0);
                                           

    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"E";
        jTextField1.setText(s0);
        
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
         String s=jTextField1.getText();
    
          s=s+"π";
        jTextField1.setText(s);
        
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
       String s0=jTextField1.getText();
       
            s0=s0+"e";
        jTextField1.setText(s0);
     
        
                                            

    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
         String s0=jTextField1.getText();
         if (inv==0 || inv%2==0){
        s0=s0+"Ans";
       
         }
         else{
             double n=Math.random();
             s0=s0+n;
         }
          jTextField1.setText(s0);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String s=jTextField1.getText();
        String c="";
        char [] s1= s.toCharArray();
        for (int i=0; i<s1.length-1; i++){
          c=c+Character.toString(s1[i]);
        }
        jTextField1.setText(c);
        
            
        
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+".";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"+";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"-";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        String s0=jTextField1.getText();
        s0=s0+"×";
        jTextField1.setText(s0);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         String s0=jTextField1.getText();
        s0=s0+"÷";
        jTextField1.setText(s0);
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    ++toggle;
                
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        String s=jTextField1.getText();
        String sa="+";
        String ss="-";
        String sd="÷";
        String sm="×";
        String ln="ln";
        String lg="log";
        String sn="sin";
        String cs="cos";
        String tn="tan";
        String ex="E";
        String e="e";
        String pi="π";
        String f="!";
        String pow="^";
        String route="√";
        String inv="Inv(";
        String per="%";
        String an="Ans";
       
                                                    
       ba=s.contains(sa);
       bs=s.contains(ss);
      bd=s.contains(sd);
         bm=s.contains(sm);
        bln=s.contains(ln);
       blog=s.contains(lg);
        bsin=s.contains(sn);
       bcos=s.contains(cs);
       btan=s.contains(tn);
        bex=s.contains(ex);
        be=s.contains(e);
       bpi=s.contains(pi);
      bf=s.contains(f);
       bpow=s.contains(pow);
      br=s.contains(route);
       binv=s.contains(inv);
       bper=s.contains(per);
       ban=s.contains(an);
      
       
       if (s.length()==1)
       { 
           if (bpi==true){
           s=pi(s);
           }
           if (be==true){
            s=e(s);
           }
           if (ban==true){
               Ans();
           
        }
           jTextField1.setText(""+s);
       }
       else
       {
          if (ban==true){
               Ans();
           
        } 
       
       
        System.out.println(s);
          if (bpi==true){
           s=pi(s);
           }
        if (be==true){
            s=e(s);
        }
       if (ba==true){
           System.out.println(ba);
           Add(s);
       }
       else
       if (bs==true){
           
           Subs(s);
       }
       else
       if(bm==true){
           mul(s);
       }
       else
       if(bd==true)
       {
           div(s);
       }
       else if(bln==true)
       {
           ln(s);
           System.out.println(blog);
       
       }
       else if(blog==true)
       {
           log(s);
           System.out.println(blog);
       
       }
       else if(bsin==true){
           sin(s);
           
       }
       else if(bcos==true){
           cos(s);
           
       }
       else if(btan==true){
           tan(s);
       }
       else if(bex==true){
           Expo(s);
       }
         else if(bf==true){
           fac(s);
         }
        else if(bpow==true){
           power(s);
         }
        else if(br==true){
           root(s);
         }
        
        else if(bper==true){
           percent(s);
         }
        else if (ban==true){
               Ans();
        }
       
       }
      
    }
    public void Add(String s){
        int index = s.indexOf("+");
        System.out.println(index);
        

        double operand1 = Double.parseDouble(s.substring(0, index).trim());
        double operand2 = Double.parseDouble(s.substring(index+1).trim());
        //System.out.println(operand1);
        //System.out.println(operand2);
        
        answer = operand1 + operand2;
        jTextField1.setText(""+answer);
        
        
    }
    public void Subs(String s){
        int index = s.indexOf("-");
        System.out.println(index);
        

        
        double operand1 = Double.parseDouble(s.substring(0, index).trim());
        double operand2 = Double.parseDouble(s.substring(index+1).trim());
        //System.out.println(operand1);
        //System.out.println(operand2);
        
        answer = operand1 - operand2;
        jTextField1.setText(""+answer);
    }
    
    public void mul(String s){
        int index = s.indexOf("×");
        System.out.println(index);
        

       
        double operand1 = Double.parseDouble(s.substring(0, index).trim());
        double operand2 = Double.parseDouble(s.substring(index+1).trim());
        
        answer = operand1*operand2;
        jTextField1.setText(""+answer);
        
    }
    public void div(String s){
        int index = s.indexOf("÷");
        System.out.println(index);
        

        double operand1 = Double.parseDouble(s.substring(0, index).trim());
        double operand2 = Double.parseDouble(s.substring(index+1).trim());
  
        answer = operand1/operand2;
        jTextField1.setText(""+answer);
    }
    public void log(String s){
        char [] s1= s.toCharArray();
          String c=Character.toString(s1[4]);
          double n=Double.parseDouble(c);
        //System.out.println(n);
          answer= Math.log(n)/Math.log(10);
          jTextField1.setText(""+answer);
    

    }
    public void ln(String s){
        char [] s1= s.toCharArray();
          String c=Character.toString(s1[3]);
          double n=Double.parseDouble(c);
        //System.out.println(n);
          answer= Math.log(n)/Math.log(Math.exp(1));
          jTextField1.setText(""+answer);
    }
    public void sin(String s){
        String c="";
        double n=0;
        
         char [] s1= s.toCharArray();
           System.out.println(toggle); 
              if (inv==0 || inv%2==0){
                  for (int i=4; i<s1.length-1; i++){
          c=c+Character.toString(s1[i]);
         }
          n=Double.parseDouble(c);
         System.out.println(n);
         if(toggle==0||toggle%2==2){
          answer= Math.sin(Math.toRadians(n));
          jTextField1.setText(""+answer);
         }
          else 
         {
            answer= Math.sin(n);
          jTextField1.setText(""+answer);
                  
         }
          }
         else {
                  for (int i=7; i<s1.length-1; i++){
          c=c+Character.toString(s1[i]);
         }
                  
          n=Double.parseDouble(c);
          if (toggle==0 || toggle%2==0){
               answer= Math.asin(n)*180/Math.PI;
             jTextField1.setText(""+answer);
              }
              else
              {
                 answer= Math.asin(n);
             jTextField1.setText(""+answer); 
              }
          }
    }
    
          
    public void tan(String s){
        String c="";
        double n=0;
        
         char [] s1= s.toCharArray();
           System.out.println(toggle); 
              if (inv==0 || inv%2==0){
                  for (int i=4; i<s1.length-1; i++){
          c=c+Character.toString(s1[i]);
         }
          n=Double.parseDouble(c);
         System.out.println(n);
         if(toggle==0||toggle%2==2){
          answer= Math.tan( Math.toRadians(n));
          jTextField1.setText(""+answer);
         }
          else 
         {
            answer= Math.tan(n);
          jTextField1.setText(""+answer);
                  
         }
          }
         else {
                  for (int i=7; i<s1.length-1; i++){
          c=c+Character.toString(s1[i]);
         }
                  
          n=Double.parseDouble(c);
          if (toggle==0 || toggle%2==0){
               answer= Math.atan(n)*180/Math.PI;
             jTextField1.setText(""+answer);
              }
              else
              {
                 answer= Math.atan(n);
             jTextField1.setText(""+answer); 
              }
          }
              
    }
    public void cos(String s){
     String c="";
        double n=0;
        
         char [] s1= s.toCharArray();
           System.out.println(toggle); 
              if (inv==0 || inv%2==0){
                  for (int i=4; i<s1.length-1; i++){
          c=c+Character.toString(s1[i]);
         }
          n=Double.parseDouble(c);
         System.out.println(n);
         if(toggle==0||toggle%2==2){
          answer= Math.cos( Math.toRadians(n));
          jTextField1.setText(""+answer);
         }
          else 
         {
            answer= Math.cos(n);
          jTextField1.setText(""+answer);
                  
         }
          }
         else {
                  for (int i=7; i<s1.length-1; i++){
          c=c+Character.toString(s1[i]);
         }
                  
          n=Double.parseDouble(c);
          if (toggle==0 || toggle%2==0){
               answer= Math.acos(n)*180/Math.PI;
             jTextField1.setText(""+answer);
              }
              else
              {
                 answer= Math.acos(n);
             jTextField1.setText(""+answer); 
              }
          }
    }
    
    public void percent(String s)
    {
         int index = s.indexOf("%");
           System.out.println(index);

           double operand1 = Double.parseDouble(s.substring(0, index).trim());
           answer=operand1/100;
           jTextField1.setText(""+answer);
           
        
    }
         public void Expo(String s)
         {
           int index = s.indexOf("E");
           System.out.println(index);

           double operand1 = Double.parseDouble(s.substring(0, index).trim());
           double operand2 = Double.parseDouble(s.substring(index+1).trim());
           answer=operand1*(Math.pow(10,operand2));
         jTextField1.setText(""+answer);
         }
        
         public void root(String s){
             int index = s.indexOf("√");
           System.out.println(index);
           
           if (index==0){

           //double operand1 = Double.parseDouble(s.substring(0, index).trim());
           double operand2 = Double.parseDouble(s.substring(index+1).trim());
           double answer=Math.sqrt(operand2);
         jTextField1.setText(""+answer);
           }
           else {
               double operand1 = Double.parseDouble(s.substring(0, index).trim());
               double operand2 = Double.parseDouble(s.substring(index+1).trim());
               answer=operand1*(Math.sqrt(operand2));
               jTextField1.setText(""+answer);
           }
             
             
         }
         public void power(String s){
             if(s.contains("^2")){
                 int index = s.indexOf("^");
              double operand1 = Double.parseDouble(s.substring(0, index).trim());
                answer= Math.pow(operand1, 2);
            jTextField1.setText(""+answer); 
             }
             else if(s.contains("^1/")){
                 int index1 = s.indexOf("^");
                 int index2 = s.indexOf("/");
                  double operand1 = Double.parseDouble(s.substring(0, index1).trim());
                  double operand2 = Double.parseDouble(s.substring(index2+1).trim());
             
                 System.out.println(operand2);

           answer= Math.pow(Math.exp (1.0/operand2),Math.log(operand1));
            jTextField1.setText(""+answer);
             } else {
             int index = s.indexOf("^");
              double operand1 = Double.parseDouble(s.substring(0, index).trim());
              double operand2 = Double.parseDouble(s.substring(index+1).trim());

           answer= Math.pow(operand1, operand2);
            jTextField1.setText(""+answer);
         }
             
         }

         public void fac(String s){
             double fac=1;
              int index = s.indexOf("!");

           double operand1 = Double.parseDouble(s.substring(0, index).trim());
           for(double i=operand1; i>1; i--)
           {
             fac=fac*i; 
           }
           answer=fac;
           jTextField1.setText(""+answer);
           
         }
        public String pi(String s){
            
            String snew;
            String so;
            
            if (ba==true || bs==true || bd==true || bm==true || bln==true || blog==true || bsin==true || bcos==true || btan==true||bex==true||be==true|| bf==true || bpow==true || br==true || binv==true || bper==true || ban==true){
           int index = s.indexOf("π");
           System.out.println(index);
           String c="";
           
           char [] s1= s.toCharArray();
           double n1= Math.PI;
           if (index==0){
               for (int i=index+1; i<s1.length; i++){
            c=c+Character.toString(s1[i]);
               }
            snew=Double.toString(n1)+c;
           
           }
        
            else   
               {
           for (int i=0; i<=index-1; i++){
            c=c+Character.toString(s1[i]);
           }
           
           
            
              
           snew=c+Double.toString(n1);
               }
               System.out.println(snew);
               }
        else 
        {
         int index = s.indexOf("π");
           System.out.println(index);
           String c="";
           
           char [] s1= s.toCharArray();
           double n1= Math.PI;
           if (index==0){
               for (int i=index+1; i<s1.length; i++){
            c=c+Character.toString(s1[i]);
               }
            snew=Double.toString(n1)+"×"+c;
           
           }
        
            else   
               {
           for (int i=0; i<=index-1; i++){
            c=c+Character.toString(s1[i]);
           }
           
           
           snew=c+"×"+Double.toString(n1);
               }
               System.out.println(snew);
               mul(snew);
               }
               
          return snew;
         }
        public String e(String s){
            
            String snew;
            String so;
           if (s.contains("□")){
               int index1=s.indexOf("e");
               int n=s.indexOf("□");
               if (index1==0){
           double operand2 = Double.parseDouble(s.substring(n+1));
                    answer=(Math.exp(operand2));
           jTextField1.setText(""+answer); 
           
               }else{
                   double operand1 = Double.parseDouble(s.substring(0, index1).trim());
                    double operand2 = Double.parseDouble(s.substring(n+1));
                    answer=operand1*(Math.exp(operand2));
           jTextField1.setText(""+answer); }
           snew=s;
               
           }
           else
            if (ba==true || bs==true || bd==true || bm==true || bln==true || blog==true || bsin==true || bcos==true || btan==true||bex==true||bpi==true|| bf==true || bpow==true || br==true || binv==true || bper==true || ban==true){
           int index = s.indexOf("e");
           System.out.println(index);
           String c="";
           
           char [] s1= s.toCharArray();
           double n1= Math.exp(1);
           if (index==0){
               for (int i=index+1; i<s1.length; i++){
            c=c+Character.toString(s1[i]);
               }
            snew=Double.toString(n1)+c;
           
           }
        
            else   
               {
           for (int i=0; i<=index-1; i++){
            c=c+Character.toString(s1[i]);
           }
           
           
            
              
           snew=c+Double.toString(n1);
               }
               System.out.println(snew);
               }
        else 
        {
         int index = s.indexOf("e");
           System.out.println(index);
           String c="";
           
           char [] s1= s.toCharArray();
           double n1= Math.exp(1);
           if (index==0){
               for (int i=index+1; i<s1.length; i++){
            c=c+Character.toString(s1[i]);
               }
            snew=Double.toString(n1)+"×"+c;
           
           }
        
            else   
               {
           for (int i=0; i<=index-1; i++){
            c=c+Character.toString(s1[i]);
           }
           
           
           snew=c+"×"+Double.toString(n1);
               }
           mul(snew);
               System.out.println(snew);
               }
        
               
          return snew;
         }
         public void Ans()
         {
             System.out.println(answer);
             String s1=Double.toString(answer);
             System.out.println(s1);
            jTextField1.setText(""+s1); 
        
               
               
         
        
        
              
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        ++inv;
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
